// Do not edit this file manually
// This file is auto-generated by scripts/generate-css-variables.js if src/styles/config/variables.css is edited

export const CSS_VARIABLES = {
  color: {
    primary: "#038fc6",
    primary_light: "#e5f7ff",
    success: "#179b03",
    success_light: "#e0ffdb",
    warning: "rgb(190, 156, 0)",
    warning_light: "#fcfade",
    error: "#e12f26",
    error_light: "#ffeaea",
    white: "#fcfcfc",
    grey_light: "#777777",
    placeholder: "#9d9d9d",
    grey_medium: "#555555",
    grey_dark: "#1c1c1c",
    disabled: "#9d9d9d",
    border: "#dddddd",
    border_light: "#e5e5e5",
  },
  font: {
    family_sans_serif: "Arial, Helvetica, sans-serif",
    family_serif: "Times, serif",
    family_monospace: '"Cousine", monospace',
    size_3xl: "3rem",
    size_2xl: "2rem",
    size_xl: "1.5rem",
    size_lg: "1.3rem",
    size_md: "1rem",
    size_sm: "0.8rem",
    size_xs: "0.7rem",
  },
  background: {
    dark: "#afafaf",
    light: "#d3d3d3",
    white: "#ffffff",
    backdrop: "rgba(0, 0, 0, 0.5)",
    backdrop_light: "rgba(0, 0, 0, 0.2)",
    surface: "#f5f7fa",
    primary_gradient: "linear-gradient(90deg, rgba(17, 117, 221, 1) 0%, rgba(17, 110, 221, 1) 23%, rgba(17, 138, 221, 1) 50%, rgba(17, 162, 221, 1) 100%)",
  },
  outline: {
    focus: "2px dashed var(--color-primary)",
  },
  opacity: {
    disabled: "0.6",
    hover: "0.8",
  },
  border: {
    radius_sm: "4px",
    radius_md: "8px",
    radius_lg: "12px",
    radius_circle: "50%",
  },
  space: {
    xs: "2px",
    sm: "4px",
    md: "8px",
    lg: "16px",
    xl: "24px",
    "2xl": "40px",
    "3xl": "64px",
  },
  box: {
    shadow: "4px 0 24px rgba(0, 0, 0, 0.1)",
  },
  z: {
    index_drawer: "10",
    index_toast: "9999",
  },
} as const;
